language: php

php:
  - 8.0

before_script: composer install --ignore-platform-reqs

script:
    - vendor/bin/phpunit

after_script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - php vendor/bin/php-coveralls -v
